name: Docker image build and push
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t registry.devbrewery.coffee/devbrewery-home
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.devbrewery.coffee
          username: ${{ secrets.REGISTRYUSER }}
          password: ${{ secrets.REGISTRYPASS }}
      - name: push image
        run: docker push registry.devbrewery.coffee/devbrewery-home
