name: Docker image build and push
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.devbrewery.coffee
          username: ${{ secrets.REGISTRYUSER }}
          password: ${{ secrets.REGISTRYPASS }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.devbrewery.coffee/devbrewery-home
